export const TICKER_NAMES: Record<string, string> = {
  RELIANCE: "Reliance Industries",
  TCS: "Tata Consultancy Services",
  INFY: "Infosys",
  HDFCBANK: "HDFC Bank",
  SBIN: "State Bank of India",
  WIPRO: "Wipro",
  ICICIBANK: "ICICI Bank",
  AXISBANK: "Axis Bank",
  KOTAKBANK: "Kotak Mahindra Bank",
  BAJFINANCE: "Bajaj Finance",
  SWIGGY: "Swiggy",
  ZOMATO: "Zomato",
  HINDUNILVR: "Hindustan Unilever",
  MARUTI: "Maruti Suzuki",
  NESTLEIND: "Nestle India",
  ASIANPAINT: "Asian Paints",
  TECHM: "Tech Mahindra",
  ITC: "ITC Ltd",
  POWERGRID: "Power Grid Corp",
  ADANIPORTS: "Adani Ports",
  TATAMOTORS: "Tata Motors",
  TATASTEEL: "Tata Steel",
  NTPC: "NTPC",
  ONGC: "ONGC",
  BHARTIARTL: "Bharti Airtel",
  SUNPHARMA: "Sun Pharmaceutical",
  BAJAJ_AUTO: "Bajaj Auto",
  DRREDDY: "Dr Reddy's Labs",
  TITAN: "Titan Company",
  LT: "Larsen & Toubro",
  ULTRACEMCO: "UltraTech Cement",
  INDUSINDBK: "IndusInd Bank",
  JSWSTEEL: "JSW Steel",
  GRASIM: "Grasim Industries",
  CIPLA: "Cipla",
  DIVISLAB: "Divi's Laboratories",
  EICHERMOT: "Eicher Motors",
  APOLLOHOSP: "Apollo Hospitals",
  HCLTECH: "HCL Technologies",
  M_M: "Mahindra & Mahindra",
  ALKYLAMINE: "Alkyl Amines Chemicals",
  HDFCLIFE: "HDFC Life Insurance",
  SBILIFE: "SBI Life Insurance",
  BAJAJFINSV: "Bajaj Finserv",
  ADANIENT: "Adani Enterprises",
  VEDL: "Vedanta",
  COALINDIA: "Coal India",
  BPCL: "Bharat Petroleum",
  IOC: "Indian Oil Corp",
  HINDALCO: "Hindalco Industries",
  TATACONSUM: "Tata Consumer Products",
  BRITANNIA: "Britannia Industries",
  PIDILITIND: "Pidilite Industries",
  HAVELLS: "Havells India",
  DMART: "Avenue Supermarts",
  IRCTC: "IRCTC",
  ZYDUSLIFE: "Zydus Lifesciences",
  TORNTPHARM: "Torrent Pharmaceuticals",
  MUTHOOTFIN: "Muthoot Finance",
  HINDCOPPER: "Hindustan Copper",
  NHPC: "NHPC",
  SAIL: "Steel Authority of India",
  BEL: "Bharat Electronics",
  HAL: "Hindustan Aeronautics",
  IRFC: "Indian Railway Finance Corp",
  PFC: "Power Finance Corp",
  RECLTD: "REC Limited",
  CANBK: "Canara Bank",
  BANKBARODA: "Bank of Baroda",
  UNIONBANK: "Union Bank of India",
  IDFCFIRSTB: "IDFC First Bank",
  FEDERALBNK: "Federal Bank",
  BANDHANBNK: "Bandhan Bank",
  CHOLAFIN: "Cholamandalam Finance",
  MOTHERSON: "Samvardhana Motherson",
  BALKRISIND: "Balkrishna Industries",
  ASTRAL: "Astral",
  TRENT: "Trent",
  NYKAA: "FSN E-Commerce (Nykaa)",
  PAYTM: "One 97 Communications (Paytm)",
  POLICYBZR: "PB Fintech (PolicyBazaar)",
  MARICO: "Marico",
  GODREJCP: "Godrej Consumer Products",
  DABUR: "Dabur India",
  COLPAL: "Colgate-Palmolive India",
  EMAMILTD: "Emami",
  IGL: "Indraprastha Gas",
  MGL: "Mahanagar Gas",
  GUJGASLTD: "Gujarat Gas",
  PETRONET: "Petronet LNG",
  GAIL: "GAIL India",
  NMDC: "NMDC",
  JINDALSTEL: "Jindal Steel & Power",
  APLAPOLLO: "APL Apollo Tubes",
  HDFCAMC: "HDFC AMC",
  NIPPONLIFE: "Nippon India Mutual Fund",
  ABSLAMC: "Aditya Birla Sun Life AMC",
  ICICIGI: "ICICI Lombard",
  ICICIPRULI: "ICICI Prudential Life",
  SBICARD: "SBI Cards",
  CAMS: "CAMS",
};

export function getTickerName(ticker: string): string | undefined {
  return TICKER_NAMES[ticker];
}
