export const TICKER_NAMES: Record<string, string> = {
  RELIANCE: "Reliance Industries",
  TCS: "Tata Consultancy Services",
  INFY: "Infosys",
  HDFCBANK: "HDFC Bank",
  SBIN: "State Bank of India",
  WIPRO: "Wipro",
  ICICIBANK: "ICICI Bank",
  AXISBANK: "Axis Bank",
  KOTAKBANK: "Kotak Mahindra Bank",
  BAJFINANCE: "Bajaj Finance",
  SWIGGY: "Swiggy",
  ZOMATO: "Zomato",
  HINDUNILVR: "Hindustan Unilever",
  MARUTI: "Maruti Suzuki",
  NESTLEIND: "Nestle India",
  ASIANPAINT: "Asian Paints",
  TECHM: "Tech Mahindra",
  ITC: "ITC Ltd",
  POWERGRID: "Power Grid Corp",
  ADANIPORTS: "Adani Ports",
  TATAMOTORS: "Tata Motors",
  TATASTEEL: "Tata Steel",
  NTPC: "NTPC",
  ONGC: "ONGC",
  BHARTIARTL: "Bharti Airtel",
  SUNPHARMA: "Sun Pharmaceutical",
  BAJAJ_AUTO: "Bajaj Auto",
  DRREDDY: "Dr Reddy's Labs",
  TITAN: "Titan Company",
  LT: "Larsen & Toubro",
  ULTRACEMCO: "UltraTech Cement",
  INDUSINDBK: "IndusInd Bank",
  JSWSTEEL: "JSW Steel",
  GRASIM: "Grasim Industries",
  CIPLA: "Cipla",
  DIVISLAB: "Divi's Laboratories",
  EICHERMOT: "Eicher Motors",
  APOLLOHOSP: "Apollo Hospitals",
  HCLTECH: "HCL Technologies",
  M_M: "Mahindra & Mahindra",
};

export function getTickerName(ticker: string): string | undefined {
  return TICKER_NAMES[ticker];
}
